export const LOAD_DOC_SUCCESS = 'LOAD_DOC_SUCCESS';
export const CREATE_DOC_SUCCESS = 'CREATE_DOC_SUCCESS';
export const UPDATE_DOC_SUCCESS = 'UPDATE_DOC_SUCCESS';
export const DELETE_DOC_SUCCESS = 'DELETE_DOC_SUCCESS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
